### ISSUE TITLE
Multiple models in tabs not saved/updated

### ISSUE THREAD

**Issue by robmies1968** [kartik-v/yii2-tabs-x#12]
Here's my problem: I have two tabs on my page and there are two models connected with it. One model for each tab.
This is how it looks in the view:

<?= TabsX::widget([
'position' => TabsX::POS_ABOVE,
'align' => TabsX::ALIGN_LEFT,
'items' => [
[
'label' => 'Client',
'headerOptions' => ['style'=>'font-weight:bold'],
'content' => $this->render('Personalia.php',['model'=>$model]),
'options' => ['id' => 'Client'],
'active' => true
],
[
'label' => 'Workflow',
'content' => $this->render('Workflow.php',['model'=>$workflowModel]),
'options' => ['id' => 'Workflow'],
], etc...

Well, this works fine, because the models are shown as they are supposed to be, in both the tabs. But when I click the submitbutton (which is a central button, so not a button for each and every tab) then my first tab gets updated ('client') but the data in the second tab stays the same ('workflow').
The button looks like this:
<?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'New') : Yii::t('app', 'Save'), ['class' => $model->isNewRecord ? 'btn-lg btn-success' : 'btn-lg btn-primary']) ?>

When I go to the update action in the controller I can see that the $_POST is set for the client model, but not for the workflow model.
The controller update looks like this:

public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $workflowModel = Workflow::findOne($id);
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
          //check to see if workflowModel via $_POST, but shows nothing
           return $this->redirect(['view', 'id' => $model->ClientID]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'workflowModel' => $workflowModel,
            ]);
        }
    }

I've set all the attributes in the workflowModel to 'safe' but that doesn't change a thing. :(
It seems I am missing something, but can't figure out what. Where can I see or check why the model's data isn't sent along my POST request?
I hope someone can help me out with this.
Thanks!

**Comment by kartik-v** [comment]
This is not related to this extension but more how you are laying out elements on your page and sending POST to server.

You must ensure all tab content are inside a single form tag so that your POST submission can read all inputs inside it.
