### ISSUE TITLE
Tab 'height property only works for position Top/Bottom

### ISSUE THREAD

**Issue by matthewdaize** [kartik-v/yii2-tabs-x#13]
The tab container's 'height' property is only used when the position is set for POS_TOP or POS_BOTTOM.

**Comment by sanjarbek** [comment]
the same problem for me too.

**Comment by kartik-v** [comment]
The left and right alignments have FLOAT LEFT and FLOAT RIGHT and will not adjust to height dynamically like the top and bottom.

A special javascript routine dynamically calculates the height of tabs as you browse and auto sets it when you use FLOAT LEFT and FLOAT RIGHT.

If you need to set a FIXED HEIGHT tab use one of the FIXED HEIGHT classes or you can set your OWN fixed height CSS by setting <a href="http://demos.krajee.com/tabs-x#usage-fixed-height">a CSS class as described in the docs here</a>.

**Comment by kartik-v** [comment]
The left and right alignments have FLOAT LEFT and FLOAT RIGHT and will not adjust to height dynamically like the top and bottom. A special javascript routine dynamically calculates the height of tabs as you browse and auto sets it when you use FLOAT LEFT and FLOAT RIGHT and hence it will not work if you set your own height.

However you can control this by using FIXED HEIGHT tabs. If you need to set a FIXED HEIGHT tab use one of the FIXED HEIGHT classes or you can set your OWN fixed height CSS by setting <a href="http://demos.krajee.com/tabs-x#usage-fixed-height">a CSS class as described in the docs here</a>.
