### ISSUE TITLE
Missing argument 3 render Dropdown

### ISSUE THREAD

**Issue by chrisschd** [kartik-v/yii2-tabs-x#14]
Missing argument 3 for yii\bootstrap\Tabs::renderDropdown(), called in /var/www/html/vet/vendor/kartik-v/yii2-tabs-x/TabsX.php on line 195 and defined

Drop Down defined as:
[
				'label'=>'<i class="glyphicon glyphicon-list-alt"></i> ' . Yii::t('vet', 'More'),
				'items'=>[
						[
								'label'=>'<i class="glyphicon glyphicons-newspaper"></i> ' . Yii::t('vet', 'Finding') ,
									    //'encode'=>false,
									    'content'=>'test4',
						],
						[
						'label'=>'<i class="glyphicon glyphicons-scale"></i> ' . Yii::t('vet', 'Weight'),
						//'encode'=>false,
						'content'=>'test5',
						],
						[
						'label'=>'<i class="glyphicon glyphicons-file"></i> ' . Yii::t('vet', 'Files'),
						//'encode'=>false,
						'content'=>'test6',
						],
					],
    ],

**Comment by kartik-v** [comment]
You have an outdated extension package version. Upgrade to latest release or cross check with dev-master.
