### ISSUE TITLE
Unable to use SwitchInput within AJAX rendered tab

### ISSUE THREAD

**Issue by matthewdaize** [kartik-v/yii2-tabs-x#18]
I am using the TabsX extension you provide and it works great.

I am using it and trying to create an AJAX tab which renders a set of controls. When the tab loads, the content does however the toggle switches do not render.

I have noticed that the assets are registered but not rendered and the required JS to activate the controls are not fired.

A sneaking suspicion of mine is it has to do with TabsX needing the response sent via JSON. I have tried changing renderPartial to renderAjax to mitigate this however it still does not cause the JS to fire. I have also tried pre-loading the assets in both the parent and the child-rendered page without success.

Have I done it completely wrong or does it not support native yii2 ajax rendering options?

Controller:
```php
public function actionFetch($id, $tab) {
    $model = $this->loadModel($id);
    $html = $this->renderPartial($tab, ['model' => $model];
    return Json::encode($html);
}
```
View - Index:
```php
<?= TabsX::widget([
    'id' => 'page-tabs',
    'items' => [
        [
            'label' => 'Tab1',
            'content' => $content1,
            'active' => true,
        ],
        [
            'label' => AjaxTab
            'linkOptions' => [
                'data-url' => Url::to(['site/fetch?id='.$id.'&tab=ajaxtab1']),
            ],
        ],
    ]
]); ?>
```
View - Tab:
```php
<?= SwitchInput::widget([
    'name' => 'space_status[enabled]',
    'pluginOptions' => [
        'size' => 'large',
        'onColor' => 'success',
        'offColor' => 'danger'
    ]
]); ?>
```

**Comment by kartik-v** [comment]
Try to reinitialize the jquery plugins in the tab after ajax content is loaded. For example you can use the [tabX.success](http://plugins.krajee.com/tabs-x#tabs-x-event-success) event. Secondly all Krajee extensions offer an easy way of reintializing plugin options. To summarize just call this at the end of your view.
```php
// set your container options
echo TabsX::widget([
    'containerOptions' => ['id' => 'container-id']
   // other tab settings
]);

// your switch input inside tab
echo SwitchInput::widget([
    'name' => 'space_status[enabled]',
    'options' => ['id' => 'switch_1'] // note this id
]);

$js = <<< EOT
    // get tabs in your container
    $container =  $('#container-id');
    $container.find('.nav-tabs li [data-toggle="tab"]').each(function () {
        var $el = $(this); //each tab
        $el.on('tabsX.success', function() { // trap tab ajax content load success
              // get your plugin widget options for all krajee widgets like this using plugin name
              var opts =  window[$('#switch-id').attr('data-krajee-bootstrapSwitch')];
              $("#switch-id").bootstrapSwitch(opts); // reinitialize switch input
        })
    })
EOT;

// Register the above js file in your view
$this->registerJs($js);
```

**Comment by matthewdaize** [comment]
That suggested code worked properly when I changed renderPartial to renderAjax in the controller... 

Is this a known requirement based on the current AJAX implementation? If so, is this the only way of doing this or is there a way of baking it into the TabsX class for handling future entities? 

Odd thing is, I did some debugging and tried removing the code to troubleshoot a separate JS issue and the buttons were still rendering properly... I am now looking into some unknown cache being used mucking the results.

Have you run into this or similar problem in the past with AJAX rendering? Any suggestions for future usage?

Thanks for all the help!

**Comment by kartik-v** [comment]
Yes this is because cache is enabled. You can use plain renderAjax and set `enableCache` to `false` in `pluginOptions` if you do not want to reinit all plugins.

However, I will try to enhance the caching method of the plugin for this to work better.

**Comment by kartik-v** [comment]
Though cache is enabled in bootstrap-tabs-x by default you can set `enableCache` to `false` in `pluginOptions` if you do not want this.

However, the problem is executing embedded scripts - [refer this SFO question](http://stackoverflow.com/questions/4619668/executing-script-inside-div-retrieved-by-ajax).

**Comment by kartik-v** [comment]
I have added a few enhancements to bootstrap-tabs-x plugin via kartik-v/bootstrap-tabs-x#11, kartik-v/bootstrap-tabs-x#12, kartik-v/bootstrap-tabs-x#13, kartik-v/bootstrap-tabs-x#14.

You can use the `successCallback` and `errorCallback` method within plugin options to easily set your reinitialization methods after ajax content is loaded. Check the [plugin options docs](http://plugins.krajee.com/tabs-x#options).

**Comment by kartik-v** [comment]
@matthewdaize - I have added a few enhancements to bootstrap-tabs-x plugin via kartik-v/bootstrap-tabs-x#11, kartik-v/bootstrap-tabs-x#12, kartik-v/bootstrap-tabs-x#13, kartik-v/bootstrap-tabs-x#14.

You can use the `successCallback` and `errorCallback` method within plugin options to easily set your reinitialization methods after ajax content is loaded. Check the [plugin options docs](http://plugins.krajee.com/tabs-x#options).

**Comment by matthewdaize** [comment]
@kartik-v - Wow, more than I ever hoped! Thanks for the prompt response and improvement. Love this and your other plugins!

The side effect of clicking the same tab and it reloading the same tab is great since it allows you to update the contents without full page refresh, or switching to an off tab and back again, or having to code a button to fire the same ajax call - quite intuitive really. :)

Thanks!!
