### ISSUE TITLE
pluginEvents don't work

### ISSUE THREAD

**Issue by mobius77** [kartik-v/yii2-tabs-x#21]
It's seems like pluginEvents doesn't work.

**Comment by kroshanin** [comment]
Change next function in TabsX.php:
public function registerAssets()
    {
        $view = $this->getView();
        TabsXAsset::register($view);
        $id = $this->containerOptions['id'];
        $script = '';
		if (!empty($this->pluginEvents)) {
            foreach ($this->pluginEvents as $event => $handler) {
                $function = new JsExpression($handler);
                $script .= "jQuery('#{$id}').on('{$event}', {$function});\n";
            }
        }
        $view = $this->getView();
		$view->registerJs($script);
   }

**Comment by kartik-v** [comment]
Plugin Events should get registered. Hope you have updated packages of **yii2-krajee-base** and **yii2-tabs-x**.

You do not need the code above...
