### ISSUE TITLE
how to validate multiple forms 

### ISSUE THREAD

**Issue by irfan03** [kartik-v/yii2-tabs-x#22]
I designed multiple forms(different for every tab) using single model in yii2-tabx-x.
now i am facing a problem of validation for every tab's form, bcoz all fields attributes of model are required. so validation fails for every form. whenever i submit.
i want to submit my forms individually
plz help.

**Comment by ber5ien** [comment]
Have you tried to add a different id's inside the active forms to see if this resolve your issue? 
http://www.yiiframework.com/doc-2.0/yii-widgets-activeform.html

$id	string	ID of the widget.

**Comment by paskuale75** [comment]
I've same issue ! I've many tabs with formGrid in it, only first form's widget are active other not ... it's an asset problem ?

**Comment by kartik-v** [comment]
This is to be entirely handled in your server code... by validating FORM SUBMISSION output from each form... I am hoping your form markup is correct and you have different forms for each tab... you must ideally trigger separate submit requests for each form (can be same action with different parameters to validate)...
