### ISSUE TITLE
tabs-x and gridview

### ISSUE THREAD

**Issue by chrisschd** [kartik-v/yii2-tabs-x#24]
Hello,

I’ve a problem with tabx and gridview, follow scenario:

Tabx:

In view file view/user/details.php and controller UserController.php
1. Item “home” is rendered by “content” with render function (_home.php), all variables will be supported from UserController.php/actionDetails which render the details.php.
2. Item “Customer” use the “linkOptions” with 'linkOptions'=>['data-url'=>\yii\helpers\Url::to(['=/app/user/customerlist, 'id'=>$model->ID])] where $model comes from the UserController.php/actionDetails.
3. Item “Products” use also the linkOptions with 'linkOptions'=>['data-url'=>\yii\helpers\Url::to(['=/app/user/productlist, 'id'=>$model->ID])] where $model comes from the UserController.php/actionDetails.

Item “Customer” and “Products” has both the GridView in use. The first page of the GridView of the “Customer” and “Product” items is ok but if I click on the second page button or enter some filter/search text it fails. The view view/user/details.php will exit, the browser load (on click of the GridView “Customer”) the text values from the UserController.php/actionCustomerlist which is a Json:encoded output (echo Json::encode($html);)

Some Code Fragments:

The ActionCustomerlist

```
public function actionCustomerlist ($id)

    {

       $searchModel = new UsercustomerSearch();

       $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

       $dataProvider->query->andWhere(['user_ID' => $id]);

       $html = $this->renderPartial('_usercustomer', [

                    'searchModel' => $searchModel,

                    'dataProvider' => $dataProvider,

                    'user_ID' => $id,

       ]);

       return Json::encode($html);

    }
```

The _usercustomer.php

```
Pjax::begin(['id' => 'usercustomer-site']);

GridView::widget([ …
]);

Pjax::end();
```

The _userproduct.php

```
Pjax::begin(['id' => 'userproduct-site']);

GridView::widget([ …
]);

Pjax::end();
```

The grid view has also an ID.

Where is my
mistake? Thanks for help.

**Comment by vovkee** [comment]
Hello, same here( Have you found any solutions?

**Comment by ber5ien** [comment]
I am not sure if this the same thing I had a problem.

I am using grid tab-x with multiple grid view and resolve the issue with filter by using Pjax settings with kartik GridView

use kartik\grid\GridView;

$customerContactsOverview= GridView::widget([
        'dataProvider' => $dataContactsProvider,    
        'filterModel'=>$searchContactsModel,  
        'autoXlFormat'=>true,
        'pjax'=>true,        
        'pjaxSettings'=>[
            'neverTimeout'=>true,
            'refreshGrid' => true,
        ],
        'export'=>[
            'fontAwesome'=>true,
            'showConfirmAlert'=>false,
            'target'=>GridView::TARGET_BLANK
        ],

**Comment by ber5ien** [comment]
I am using the following and it works.

echo TabsX::widget([
    'position' => TabsX::POS_ABOVE,
    'align' => TabsX::ALIGN_LEFT,
    'encodeLabels'=>false,
    'enableStickyTabs' => true,
    'stickyTabsOptions' => [
      // 'selectorAttribute' => "data-target",
        //'backToTop' => true,
    ],
 
    'items' => [
        [
            'label'=>'<i class="glyphicon glyphicon-home"></i> Details',
            'content' => $customerOverview,
           
        ],
        [
            'label'=>'<i class="glyphicon glyphicon-list-alt"></i> Tickets',
            'content' => $ticketsOverview,                       
        ],
        [
            'label'=>'<i class="glyphicon glyphicon-list-alt"></i> Projects',
            'content' => $projectsOverview,                       
        ],
        [
            'label'=>'<i class="glyphicon glyphicon-list-alt"></i> Contacts',
            'content' => $customerContactsOverview,           
            
        ],   
        [
            'label'=>'<i class="glyphicon glyphicon-list-alt"></i> Users',
            'content' => $assignedUsers,           
            
        ],       
    ],
]);  

 $customerContactsOverview= GridView::widget([
        'dataProvider' => $dataContactsProvider,    
        'filterModel'=>$searchContactsModel,  
        'autoXlFormat'=>true,
        'pjax'=>true,        
        'pjaxSettings'=>[
            'neverTimeout'=>true,
            'refreshGrid' => true,
        ],
        'export'=>[
            'fontAwesome'=>true,
            'showConfirmAlert'=>false,
            'target'=>GridView::TARGET_BLANK
        ], 
        'columns' => [                    
            [
            'class' => '\kartik\grid\SerialColumn',
            ],
            [                
                'attribute' => 'contact_id',                         
                'format' => 'raw',
                'value'=>function ($model, $key, $index, $widget) {                 
                  return Html::a($model->contact_id, ['customers-contacts/view','id' => $model->contact_id], [
                'title'=>'View Contact detail',                
            ]);
            }, 
            ],                    
            'contact_name',            
            'contact_email',            
            'contact_tel',
             [
                'attribute' => 'contact_type',        
                'value' => function ($model){
                $types=null;  
                 if(isset($model->contact_type) and !empty($model->contact_type)){
                    $model['contact_type'] = str_split($model->contact_type,1);   
                    foreach($model->contact_type as $type){
                        if(isset(Yii::$app->params['contacttypes'][$type])){
                            $types = $types.Yii::$app->params['contacttypes'][$type]." ";                        
                        }                    
                    }
                    return $types;
                    }
                },
                'filterType'=>GridView::FILTER_SELECT2,
                    'filterWidgetOptions'=>[                         
                        'theme' => 'krajee',
                        'options' => ['placeholder' => 'Type ...'],
                        'data' => Yii::$app->params['contacttypes'],
                        'pluginOptions'=>[
                            'allowClear' => true,                             
                        ],
                ],           
            ], 
                            
        ],//columns
         'panel' => [
        'heading'=>'<h3 class="panel-title"><i class="glyphicon glyphicon-list"></i> Customer Contacts</h3>',
        'type'=>'info',        
        
    ],
     'toolbar' =>  [
            [
            'content'=>
                Html::a('<i class="glyphicon glyphicon-plus"></i>',['customers-contacts/create'], [
                    'type'=>'button', 
                    'title'=>'Create New Ticket',
                    'class'=>'btn btn-success',
                    'action' => 'create',
                ]),
            ],    
            '{export}',
            '{toggleData}'
    ],
        'responsive'=>true,
        'hover'=>true,   
    ]);
