### ISSUE TITLE
Support Items:visible property

### ISSUE THREAD

**Issue by matthewdaize** [kartik-v/yii2-tabs-x#26]
In the upcoming Yii release 2.0.5, the tab's items property will support the "visible" property to allow programmatic hiding of tabs (eg. authorization checks, context, etc.)

Will TabsX support it in the same way? It looks to be an early loop break if the visible parameter is present & set to false.

**Comment by kartik-v** [comment]
> Will TabsX support it in the same way?
Yes it would in from future releases.

**Comment by kartik-v** [comment]
Resolved via [upgrade to release v1.2.1](https://github.com/kartik-v/yii2-tabs-x/commit/0a371000c4b4177add5a6b8bc8e91eb3e5bf65ea).
