### ISSUE TITLE
Active Ajax Tab Label - Press to reload tab

### ISSUE THREAD

**Issue by matthewdaize** [kartik-v/yii2-tabs-x#27]
Currently, you need to browse off to a different tab and select back to reload its' dynamic contents.

It would be very useful to add the ability (optional) to allow clicking on an active ajax header tab and have it reload the contents of the pane.

**Comment by kartik-v** [comment]
This already exists. Its dependent on your ajax cache settings. The plugin by default has ajax caching enabled for each tab. You can the [pluginOptions['enableCache']](http://plugins.krajee.com/tabs-x#option-enableCache) setting  to `false` so that clicking a tab will always fire the ajax request.

**Comment by matthewdaize** [comment]
That's great. Thank you!
