### ISSUE TITLE
can you give a full example for ajax tabs

### ISSUE THREAD

**Issue by asoqa** [kartik-v/yii2-tabs-x#3]
```
I used the linkOptions to send an ajax request, but I don't know how and where to use the data returned. for example:
```

view

```
    $item['label'] = $type;
    $item['content'] = '';
    $item['linkOptions'] = ['data-url'=>\yii\helpers\Url::to(['/datamine/graph'])];
...
    echo TabsX::widget([
        'items'=>$this->params['items'],
        'position'=>TabsX::POS_LEFT,
        'bordered'=>true,
        'sideways'=>false,
        'encodeLabels'=>false
    ]);

```

controller

```
return json_encode(['content2'=>'test']);
```

But the content displays empty, not the json string

**Comment by carlojo** [comment]
@kartik-v good morning, I'm trying to use your yii2 tabsx with ajax call. 
In the view I have this:
`$items = [
    [
        'label'=>'<i class="glyphicon glyphicon-home"></i> Home',
        'content'=>$content1,
        'active'=>true,
        'linkOptions'=>['data-url'=>  yii\helpers\Url::to(['/secciones/dashboard-tabs-data','id'=>1])]
    ],
    [
        'label'=>'<i class="glyphicon glyphicon-user"></i> Profile',
        'content'=>$content2,
        'linkOptions'=>['data-url'=>  yii\helpers\Url::to(['/secciones/dashboard-tabs-data','id'=>2])]
    ],    
];
echo TabsX::widget([
        'items'=>$items,
        'position'=>TabsX::POS_LEFT,
        'encodeLabels'=>false
    ]);
` 

in the controller for fetching data I have this:
`return json_encode($this->renderAjax('_dashboard-graficos',[
            'id'=>$id
        ]));`

And in that partial view I have ChartJs:
`<?= ChartJs::widget([
        'type' => 'doughnut',
        'options' => [
            'height' => $hChart,
            'width' => $wChart
        ],
        'data' => [
            'labels' => ArrayHelper::getColumn(VwSeccionesActivasResumen::find()->where(['codigoTipoJornada'=>$id])->all(), 'nombreCompleto'),
             'datasets' => [
                 [
                   'data'=>ArrayHelper::getColumn(VwSeccionesActivasResumen::find()->where(['codigoTipoJornada'=>$id])->all(), 'cantidadSecciones'),
                   'backgroundColor'=> [
                        "#36A2EB",
                        "#FFCE56",
                        "#FF6384"
                    ],
                    'hoverBackgroundColor'=> [
                        "#36A2EB",
                        "#FFCE56",
                        "#FF6384"
                    ]
                 ],

             ]
        ]
    ]);?>`

In this view I also have some other data that is fetch with models.

When I trigger the ajax call from the Tabs the information is showing but the ChartJs never appears. This only happens whith this ChartJs when I used this ajax call, if I use ChartJs directly it works fine. Do you know what can be happening with ajax calls and chartjs?
