### ISSUE TITLE
Error with pluginDestroyJs after updating krajee-base

### ISSUE THREAD

**Issue by jay-leno** [kartik-v/yii2-tabs-x#32]
After upgrading yii2-krajee-base to 1.8.2 the following error is occurring both in my code and on the demo page as well.

Getting unknown property: kartik\tabs\TabsX::pluginDestroyJs

Reverting to 1.8.1 resolves the issue for now.

**Comment by kartik-v** [comment]
You must upgrade to release v1.2.2 of the tabs-x plugin.

**Comment by kartik-v** [comment]
You have an outdated release. You must upgrade to release v1.2.2 of the yii2-tabs-x extension.
