### ISSUE TITLE
Add branch-alias

### ISSUE THREAD

**Issue by LAV45** [kartik-v/yii2-tabs-x#33]
Please add branch-alias to your composer.json
Example: https://github.com/yiisoft/yii2/blob/master/composer.json#L91-L93
This option allows to update your application to latest valid version.

P.S. This is the same problem as all the rest of your projects.

**Comment by kartik-v** [comment]
It is not probably mandatory for everyone to want to install the unstable dev version.

But it surely allows an option for folks to install the latest `dev-master`. So recording an enhancement.

**Comment by LAV45** [comment]
For theis moment, to always have the last upgrade to have all your apps to sign such a version
```
"kartik-v/yii2-tabs-x": "dev-master as 1.2.x-dev",
```
It is not very convenient and not many people know about this possibility and therefore they can't get the hot fix if you don't place it next version.
