### ISSUE TITLE
Printable tabs.

### ISSUE THREAD

**Issue by SamMousa** [kartik-v/yii2-tabs-x#36]
Hey Kartik,

For one of my projects I need printable tabs; while considering if I want to implement this as a separate widget subclassing either your or Yii's official tab widget, I thought I'd just ask if you are interested in this as well.

The functionality I envision is as follows:
1. Each tab header is duplicated in the tab-content as well, but with a printing only class `.visible-print-block`.
2. Each tab navigation element gets a class `.hidden-print`
3. Each tab content div gets a `.visible-print-block` class. 

This way when printing tabs, the navigation will be hidden and each tab will be printed with the appropriate header line.

This could all be toggled with a boolean configuration option for the tabs widget.

If you'd like this in your tab widget I can make a PR!

**Comment by kartik-v** [comment]
Sure you can submit a PR for this.

**Comment by SamMousa** [comment]
#37
