### ISSUE TITLE
Handling Bootstrap active tabs via URL

### ISSUE THREAD

**Issue by yafater** [kartik-v/yii2-tabs-x#39]
I'm using Tab-x. my codes are these

$items = [

```
[
    'label'=>'<i class="fa fa-plus-circle"></i> '.Yii::t('app', 'Create Category'),
    'linkOptions'=>['data-url'=>Url::to(['/site/createcategory'])],
    'active'=>TRUE
],
```

];
// Ajax Tabs Above
echo TabsX::widget([
    'items'=>$items,
    'position'=>TabsX::POS_ABOVE,
    'encodeLabels'=>false
]);
I want to show my active item that handles via url when my page is loading.How can I do that?

**Comment by kullar84** [comment]
@yafater Enable sticky tabs

**Comment by tsirakis** [comment]
@kullar84 even if you enable the sticky tabs how you trigger the click on ajax content?

**Comment by aikon2** [comment]
`echo TabsX::widget([
 ...
    'enableStickyTabs' => true,`
