### ISSUE TITLE
can not make height smaller

### ISSUE THREAD

**Issue by asoqa** [kartik-v/yii2-tabs-x#4]
I set the height size_tiny, but the height has no change. The element's html class has been changed to "tabs-x tabs-above tab-align-right tab-height-xs"
```
    echo TabsX::widget([
        'items' => $items,
        'height'=>TabsX::SIZE_TINY,
        'position' => TabsX::POS_ABOVE,
        'align' => TabsX::ALIGN_RIGHT,
        'bordered' => false,
        'encodeLabels' => false
    ]);
```

**Comment by kartik-v** [comment]
You need to debug your environment if the CSS files are loaded properly from the plugin OR if you have browser caching issues not rendering the styles properly.
