### ISSUE TITLE
Ajax call - don't load any widgets assets

### ISSUE THREAD

**Issue by paskuale75** [kartik-v/yii2-tabs-x#45]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-tabs-x.
- [x] This is not an usage question. I confirm having gone through and read the [documentation and demos](http://demos.krajee.com/tabs-x).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [x] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Insert form-builder widget in _form view
2. create tabs items with data-url option (ajax call)
3.

## Expected behavior and actual behavior

When I follow those steps, I see... N tabs (first active and worked) the other tabs have unarmed widgets in it ! I also tried with renderAjax instead of renderPartial but without success (layout break) ! I set a ID to $form don't solve !

I was expecting...

#### Browsers

- [ ] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-tabs-x version: last

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/tabs-x)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-tabs-x without other plugins.

**Comment by buttflattery** [comment]
up

**Comment by strtob** [comment]
I have the same problem.

The tabs will be shown, first is set by content param correctly. As soon as I press a tab, firefox debug show me the call an the response is correct (I've also tried with simple "test" string as return). 

The spinner is working on, but no result will be shown in the content area. also, no js error in the console is given.
