### ISSUE TITLE
Change active tab on click in form

### ISSUE THREAD

**Issue by tigrasti** [kartik-v/yii2-tabs-x#46]
Is it possible to change active tab on submiting form above tabx, based on post data?

**Comment by aikon2** [comment]
my trick, in submitting form create variable step for change active tab: 
`
if( $model->load($request->post()) ) {
if( $model->save() ){
$step +=1;
return $this->redirect(['update',  'step' => $step, '#' => 'w0-tab' . $step]);
}
}`
