### ISSUE TITLE
missing hashVarLoadPosition property

### ISSUE THREAD

**Issue by odai-alali** [kartik-v/yii2-tabs-x#47]
Getting unknown property: kartik\tabs\TabsX::hashVarLoadPosition

TabX uses WidgetTrait   which has the method **registerPluginOptions($name)**
In this method the property **hashVarLoadPosition** is called which gives an error because TabsX does not inherits from base Widget i think

http://demos.krajee.com/tabs-x gives an internal server error too

**Comment by phuong17889** [comment]
me too
```
Unknown Property – yii\base\UnknownPropertyException

Getting unknown property: kartik\tabs\TabsX::hashVarLoadPosition
```
ref: https://github.com/kartik-v/yii2-krajee-base/commit/008f59fec9f5e6adf2d25c76766b3657642c0692#diff-69f1fbfd149df4f64be277b44c24510dR113

**Comment by odai-alali** [comment]
you can use version 1.8.8 for now. this property is added with version 1.8.9

**Comment by kartik-v** [comment]
This is resolved. Get the updated build.
