### ISSUE TITLE
PHP Fatal Error – yii\base\ErrorException  Class 'kartik\tabs\View' not found

### ISSUE THREAD

**Issue by aenima700** [kartik-v/yii2-tabs-x#48]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of yii2-tabs-x.
- [ ] This is not an usage question. I confirm having gone through and read the [documentation and demos](http://demos.krajee.com/tabs-x).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Load page with TabX

## Expected behavior and actual behavior

I just load my page and I'm find the error:

PHP Fatal Error – yii\base\ErrorException

Class 'kartik\tabs\View' not found

I only made a composer update...

I was expecting...

#### Browsers

- [ x] Google Chrome
- [x ] Mozilla Firefox
- [x ] Internet Explorer
- [ x] Safari

#### Operating System

- [x ] Windows
- [x ] Mac OS X
- [x ] Linux
- [x ] Mobile

#### Libraries

- jQuery version:
- yii2-tabs-x version:

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/tabs-x)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-tabs-x without other plugins.

**Comment by kartik-v** [comment]
Resolved via a987ec0.
