### ISSUE TITLE
Not updated version of dependent bootstrap-tabs-x

### ISSUE THREAD

**Issue by sviluppo** [kartik-v/yii2-tabs-x#49]
When you install/update trough composer **yii2-tabs-x** he will download the Version **1.3.2** of **bootstrap-tabs-x** because this one had not **1.3.3** like latest release and **yii2-bas-x** not use, of course, the **dev** one.

**Comment by dmkdesign** [comment]
Composer.json file needs to be updated to force "kartik-v/bootstrap-tabs-x": "1.3.3" otherwise bootstrap 4 css won't be available in asset bundle.
