### ISSUE TITLE
Call to undefined method kartik\tabs\TabsXAsset::registerBundle()

### ISSUE THREAD

**Issue by skugarev** [kartik-v/yii2-tabs-x#62]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of yii2-tabs-x.
- [ ] This is not an usage question. I confirm having gone through and read the [documentation and demos](http://demos.krajee.com/tabs-x).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

#### Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-tabs-x version:

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/tabs-x)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-tabs-x without other plugins.

**Comment by skugarev** [comment]
Call to undefined method kartik\tabs\TabsXAsset::registerBundle()

**Comment by skugarev** [comment]
http://joxi.net/Dr81LEaF4jRGPm

**Comment by kartik-v** [comment]
You must update all extensions and dependencies via `composer` - else you will face errors - it seems you only have updated `yii2-tabs-x` manually and not the dependencies.

Run `composer update` to get all updated dependencies like `yii2-krajee-base`
