### ISSUE TITLE
css file is lost

### ISSUE THREAD

**Issue by Nickolay911** [kartik-v/yii2-tabs-x#71]
Hi! I am try to use last and dev versions:
  - Installing kartik-v/bootstrap-tabs-x (dev-master fb38942): Cloning fb3894222c
  - Installing kartik-v/yii2-tabs-x (dev-master 7f3232f): Cloning 7f3232f338

in any case vertical tabs just not working, because css file is lost
my view:
```
<?= TabsX::widget([
    'items'=>$items,
    'position'=>TabsX::POS_LEFT,
    'encodeLabels'=>false
]) ?>
```
but see just horizontal tabs.

Looks like, after rollback it commit 
https://github.com/kartik-v/yii2-tabs-x/commit/46817b7efa2b0ce8debd2be722ff779a6f900aba#diff-5f8f89146777c404b2acb7b4b11b6251de40847e69bc4a8aaa0a46412d341720

all works fine.

**Comment by kartik-v** [comment]
Thanks will revert the pull request that was submitted.
