### ISSUE TITLE
tabsX.click plugin event not working after updating package

### ISSUE THREAD

**Issue by AlanHeckinJohnston** [kartik-v/yii2-tabs-x#73]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-tabs-x.
- [x] This is not an usage question. I confirm having gone through and read the [documentation and demos](http://demos.krajee.com/tabs-x).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

```
$tabsXClick = "

 function()
{
 console.log('clicked');
}

";

echo TabsX::widget([
   "pluginEvents" => ["tabsX.click" => $tabsXClick],
   // rest of configuration here....
]);
```

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

#### Browsers

- [ ] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [x] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

#### Libraries

- jQuery version: no version specified in bower, assuming most recent
- yii2-tabs-x version: 1.2.8

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/tabs-x)
- [ ] The bug happens consistently across all tested browsers
- [x] This bug happens when using yii2-tabs-x without other plugins.

**Comment by KennyChan94P** [comment]
instead of "tabsX.click" => $tabsXClick, you can try with "tabsX:click" => $tabsXClick
it should be a typo, instead of ".", use ":"
