### ISSUE TITLE
Doesn't seem to work with BS 5.x setting

### ISSUE THREAD

**Issue by synatree** [kartik-v/yii2-tabs-x#74]
It looks like the logic for BS 5.x is not fully implemented;

1) Tries to use `kartik\bs4dropdown\Dropdown` which is not in `composer.json`
2) Probably should use `! isBs(3)` instead of `isBs4()` call...

I'm attempting to make it work and submit a PR.

**Comment by spo0okie** [comment]
Same. Updated bootstrap3 -> 5. TabsX not switching tabs from current active.

**Comment by kartik-v** [comment]
Folks there is an enhancement needed to the core bootstrap-tabs-x plugin for BS5.x related support. This is almost done in the repo kartik-v/bootstrap-tabs-x. Once that is done this repo will also be updated.

**Comment by kartik-v** [comment]
Enhanced via new release to support BS 5.x
