### ISSUE TITLE
Dropdown divider in TabsX

### ISSUE THREAD

**Issue by bbushong** [kartik-v/yii2-tabs-x#76]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-tabs-x.
- [x] This is not an usage question. I confirm having gone through and read the [documentation and demos](http://demos.krajee.com/tabs-x).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

I'm assuming that TabsX is built on top of NavX (https://demos.krajee.com/nav-x#usage), but am having problem with inserting dividers. Example:

```
$items = [
	[
		'label'=>'<i class="fas fa-clipboard"></i> First Menu',
		'content'=>$tab1
	],
	'<div class="dropdown-divider"></div>',
	[
		'label'=>'<i class="fas fa-clipboard"></i> Second Menu',
		'content'=>$tab2
	],
]
```

And I get back:
```
Invalid Configuration – yii\base\InvalidConfigException
The 'label' option is required.
```

Showing the TabsX expects a label in the array. Does TabsX support this mechanism?

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/tabs-x)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using yii2-tabs-x without other plugins.

**Comment by kartik-v** [comment]
dividers are supported only in dropdowns not in tabs. If you have a dropdown submenu within a tab - then you may be able to insert dividers for the sub items there.

**Comment by bbushong** [comment]
First - I want to say thank you to @kartik-v for all the incredible work you've done.

Second - you are correct that the above is a bad example. I put together the example too quickly. Here is a better demonstration of what I am trying to do:
```
$items = [
	[
		'label'=>'<i class="fas fa-clipboard"></i> Overview',
		'content'=>$tab1,
	],
	[
		'label'=>'<i class="fas fa-quote-left"></i> Stories',
		'content'=>$tab2,
	],
	[
		'label'=>'<i class="fas fa-plug"></i> Connections',
		'content'=>$tab3,
	],
	[
		'label'=>'<i class="fas fa-list-alt"></i> Media Files',
		'items'=>
		[
			[
				'label'=>'Project Images',
				'content'=>$tab7a,
			],
			[
				'label'=>'Video Interviews',
				'content'=>$tab7b,
			],
			[
				'label'=>'B-Roll Footage',
				'content'=>$tab7c,
			],
			'<div class="dropdown-divider"></div>',
			[
				'label'=>'Final Deliverables',
				'content'=>$tab7f,
			],
			 
		],
	],
	[
		'label'=>'<i class="fas fa-sticky-note"></i> Notes',
		'content'=>$tab8,
	],

];
```

and I get back the following error:
```
Invalid Configuration – yii\base\InvalidConfigException
The 'label' option is required.
```

Looking at the documentation for TabsX, I don't see the ability to parse this properly, whereas I do see it in the documentation on NavX (https://demos.krajee.com/nav-x#usage). Also, based on the code I see here: https://github.com/kartik-v/yii2-tabs-x/blob/c968409e2820339b7084890cb018376687fed408/src/TabsX.php#L326-L334 and here: https://github.com/kartik-v/yii2-tabs-x/blob/c968409e2820339b7084890cb018376687fed408/src/TabsX.php#L395 - it seems like label is required for both menu/submenu.

So again, thank you Kartik! I'll see if I can find away around this another way as it does not appear "baked" in.
