### ISSUE TITLE
Can't make active tab auto load

### ISSUE THREAD

**Issue by rizkiarm** [kartik-v/yii2-tabs-x#9]
I've been following your documentation in ajax tabs implementation to no avail. Somehow the active tab isn't automatically loaded on start. Here is my code:

``` php
<?= TabsX::widget([
    'items' => [
        [
            'label' => 'Home',
            'linkOptions' => ['data-url' => Url::to(['tab-home'])],
            'active' => true,
            'options' => ['id' => 'home'],
        ],
        [
            'label' => 'Progress',
            'linkOptions' => ['data-url' => Url::to(['tab-progress'])],
            'options' => ['id' => 'progress'],
        ],
        [
            'label' => 'Contact',
            'linkOptions' => ['data-url' => Url::to(['tab-contact'])],
            'options' => ['id' => 'contact'],
        ],
    ],
    'position' => TabsX::POS_ABOVE,
    'encodeLabels' => false
]) ?>
```

Is there something wrong with my code?

**Comment by liamgcarter** [comment]
$this->registerJs(' 
$("document").ready(function() {
    setTimeout(function() {
    	$(".tabs-krajee").find("li.active a").click();
    },10);
});', \yii\web\View::POS_READY);

**Comment by MarcoDuizer** [comment]
I have the same problem. The active tab is not loading the content from the renderpartial part in the controller. I want to fill the first tab with the content of the renderpartial action in the controller. How can i do that without adding addition javascript? I don't get it what to do with the description in OPTION 1. Only for the first active tab i need to do something to get it loaded on opening of the page the first time. The other tabs will only be opened by clicking on the tabs so they are fine. Can you give a code example on how to do option 1 please?
By the way great extensions that you created, using a lot of them!! Thanks for the great work!!

**Comment by kartik-v** [comment]
I thought it is straightforward... anyway you can have a look at the [documentation and demo for TabsX usage for ajax tabs](http://demos.krajee.com/tabs-x#usage-ajax). You just need to provide the `content` property of the active tab within the `items` array which you are showing on load.

**Comment by MarcoDuizer** [comment]
Hi Kartik,
Great!!!! thanks for the help, I just needed to get some support to go in the right direction and found it. I got it working now with the content created (renderPartial) in the controller and passed with the $content variable.
Keep up the great work, love your extensions!!

**Comment by deshario** [comment]
@liamgcarter 
I used to renderAjax() and  return Json::encode($rendered_data); from controller
and used your method to auto reload tabs ... everythings work perfect ...  but when i click into other tabs after first click ... Content (Maps) dont show properly ....

If I have 3 tabs => Tab1,Tab2,Tab3 .... I register js to auto load tab1 by default ...
{Every Tabs used url to load data} ..... After Tab1 auto load and then if i click tab2 it also work fine .. but if then i click tab3 the content dont load properly ... 

After first auto load ... if i clicked to the last tab(TAB3) ... and then every tabs working fine ... 
After first auto load ... if i clicked to the TAB2 ... and then Tab3 have some problem

Is there anyway that i can load data properly ... my data includes google map

**Comment by wizmtupu** [comment]
Its 2021 and i happen to have come across this problem when executing the tabx from Kartik. By the way, Kartik, thanks for your work. I basically implemented the following in yii2 MVC without writing any side script.
1. You have an action button that opens to a view with your tabx.....lets name this button "car profile button"
2.  Lets say in the view that has tabx, you want the "active" tab to pull data from a view called "Engine_specs" by default once the car profile button is clicked and the view that has tabx is displayed;
3. In your controller, you would have the following method for the view

  ```
 public function actionEngine_specs($id)
    {
        return $this->renderPartial('engine_specs', //Partially renders a view file called "engine specs" to be displayed on first tab
        [   
            'model' => $this->findModel($id),
        ]);
    }
```

4. Finishing up in controller, the car profile button uses below action method to open a view/page called "car profile" that has  tabx with active tab pulling "engine specs" view file.

```
  public function actionCar_profile($id)
    {
        return $this->render('car_profile', [              //this renders you view called "car_profile" that has the tabx
            'model' => $this->findModel($id),         // pass "model" variable for the model data
            'tab1content' => $this->actionEngine_specs($id)  // pass "tab1content" variable for a view action called "Engine_specs"
        ]);
    }
```

5. In "car_profile" view, you will have your tabx set like below
 ```
 <?= TabsX::widget([
    'items' => [
        [
            'label' => 'Tab1',
            'content' =>$tab1content,              // $tab1content is a variable passed via controller as shown above
            'active' => true,
            'options' => ['id' => 'home'],
        ],
        [
            'label' => 'Tab2',
            'linkOptions' => ['data-url' => Url::to(['tab-progress'])],
            'options' => ['id' => 'progress'],
        ],
        [
            'label' => 'Tab3',
            'linkOptions' => ['data-url' => Url::to(['tab-contact'])],
            'options' => ['id' => 'contact'],
        ],
    ],
    'position' => TabsX::POS_ABOVE,
    'encodeLabels' => false
]) ?>
```

Hope this helps someone out there.
